add ignore config
Jeffmen/glue pull request #5
Opened 2022-03-26 08:55 UTC by jomatto

config about ignore

2022-03-27 13:11 UTC, jomatto commented
rrrr

2022-03-28 06:45 UTC, Jeffmen commented
lock

2022-04-03 09:04 UTC, Jeffmen commented
vvvv

2022-05-10 03:07 UTC, Jeffmen reviewed
test

2022-05-10 03:10 UTC, Jeffmen requested changes, later dismissed
edit

2022-05-10 03:10 UTC, Jeffmen commented on .gitignore
> +/library/plugin/build
commet

2022-05-10 03:10 UTC, Jeffmen commented on .gitignore
> +/library/plugin/build
很好

2022-05-10 03:21 UTC, Jeffmen commented
locked

2022-05-10 04:17 UTC, Daojiand reviewed
comment from daojiand

2022-05-10 06:43 UTC, Jeffmen commented
![Screenshot_20220509-115242.jpg](https://user-images.githubusercontent.com/1762668/167564790-74a85b23-6624-43e0-babd-5ae80f30c376.jpg)

2022-05-10 07:40 UTC, closed without merging